steps:
  # Install dependencies
  - name: 'composer:2'
    args: ['install', '--no-dev', '--no-interaction']

  # Copy environment file
  - name: 'debian'
    args: ['cp', '.env.example', '.env']

  # Generate app key
  - name: 'php:8.4'
    entrypoint: php
    args: ['artisan', 'key:generate', '--force']

  # Run migrations
  - name: 'php:8.4'
    entrypoint: php
    args: ['artisan', 'migrate', '--force']

  # Run seeders
  - name: 'php:8.4'
    entrypoint: php
    args: ['artisan', 'db:seed', '--force']

  # Install and build frontend assets
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']

  # Build and push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lawn-app', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lawn-app']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'lawn-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/lawn-app'
      - '--region'
      - 'europe-west3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/lawn-app'
