steps:
  # Installiere Abhängigkeiten
  - name: 'composer:2'
    args: ['install', '--no-dev', '--optimize-autoloader']

  # Kopiere Umgebungsdatei
  - name: 'debian'
    args: ['cp', '.env.example', '.env']

  # Generiere App-Schlüssel
  - name: 'php:8.4'
    entrypoint: php
    args: ['artisan', 'key:generate', '--force']

  # Frontend-Assets
  - name: 'node:20'
    entrypoint: npm
    args: ['ci']
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']

  # Container-Image bauen und pushen
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lawn-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lawn-app']

  # Cloud Run Deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'lawn-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/lawn-app'
      - '--region'
      - 'europe-west3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'APP_NAME=LawnManagement,APP_ENV=production,APP_DEBUG=false,DB_CONNECTION=sqlite'

images:
  - 'gcr.io/$PROJECT_ID/lawn-app'
